//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5420
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siglop.Menu_Principal.Gestion_de_Stock {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Gestion_de_Stock {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Gestion_de_Stock() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Siglop.Menu_Principal.Gestion_de_Stock.Gestion de Stock", typeof(Gestion_de_Stock).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static bool CheckBoxColum_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("CheckBoxColum.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool Column1_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column1.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool Column10_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column10.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool Column11_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column11.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool Column12_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column12.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool Column13_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column13.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool Column2_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column2.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool Column3_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column3.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool Column4_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column4.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool Column5_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column5.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool Column6_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column6.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool Column7_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column7.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool Column8_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column8.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        public static bool Column9_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column9.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
    }
}
